name: datascience-bootcamp
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- ipykernel=6.9.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.1
- jupyterlab=3.4.3
- matplotlib=3.5.2
- pandas-profiling=3.2.0
# - pip=21.2.4
- python=3.9.7
# - pytorch=1.7.0
- seaborn=0.11.2
- sweetviz=2.1.3
- plotly=5.9.0
- umap-learn=0.5.3
- scikit-learn=1.1.1
# - imblearn
# - xgboost=1.6.1
